"use client";

import { useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, Bell, CalendarDays, ChevronRight, CircleHelp, Grid2X2, LayoutDashboard, MapPin, Menu, Plus, Search, Settings, Trophy, Users, X } from "lucide-react";
import { currentUser, events, groups, leaderboard, recentResults, type DemoEvent } from "@/lib/demo";

const navItems = [
  { label: "Dashboard", icon: LayoutDashboard },
  { label: "My games", icon: CalendarDays, count: 2 },
  { label: "Groups", icon: Users },
  { label: "Leaderboards", icon: Trophy },
  { label: "Match history", icon: Activity },
];

function Logo() {
  return <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#1b211e] text-sm font-black tracking-tight text-[var(--lime)]">PW</div><div><p className="text-[15px] font-extrabold tracking-tight">Pickleball<span className="text-[var(--lime-deep)]">Wolves</span></p><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[var(--ink-soft)]">Find your pack</p></div></div>;
}

function EventCard({ event, onToggle }: { event: DemoEvent; onToggle: (id: string) => void }) {
  const color = event.accent === "lime" ? "#d8f24e" : event.accent === "coral" ? "#f17e62" : "#8cc9df";
  return <article className="panel group relative overflow-hidden rounded-[20px] p-5 transition-transform hover:-translate-y-1 sm:p-6">
    <div className="absolute inset-x-0 top-0 h-1" style={{ background: color }} />
    <div className="mb-5 flex items-start justify-between gap-4"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink-soft)]">{event.dateLabel}</p><h3 className="text-[17px] font-bold tracking-tight">{event.title}</h3></div><span className="rounded-full px-2.5 py-1 text-[11px] font-bold" style={{ background: `${color}55` }}>{event.format}</span></div>
    <div className="space-y-2 text-sm text-[var(--ink-soft)]"><p className="flex items-center gap-2"><CalendarDays size={15} />{event.timeLabel}</p><p className="flex items-center gap-2"><MapPin size={15} />{event.location}</p></div>
    <div className="mt-5 flex items-center justify-between border-t border-[var(--line)] pt-4"><span className="text-xs font-semibold text-[var(--ink-soft)]"><strong className="text-[var(--foreground)]">{event.spotsLeft}</strong> spots left</span><button onClick={() => onToggle(event.id)} className={`rounded-full px-4 py-2 text-xs font-bold transition-colors ${event.attending ? "bg-[var(--lime)] text-[#1b211e]" : "bg-[#1b211e] text-white hover:bg-[#344037]"}`}>{event.attending ? "You’re in" : "Join game"}</button></div>
  </article>;
}

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [activeNav, setActiveNav] = useState("Dashboard");
  const [eventList, setEventList] = useState(events);
  const [filter, setFilter] = useState<"All" | "Doubles" | "Mixed doubles">("All");
  const toggleEvent = (id: string) => setEventList((items) => items.map((item) => item.id === id ? { ...item, attending: !item.attending, spotsLeft: item.attending ? item.spotsLeft + 1 : Math.max(0, item.spotsLeft - 1) } : item));
  const visibleEvents = eventList.filter((event) => filter === "All" || event.format === filter);

  return <div className="min-h-screen bg-[var(--background)] noise lg:flex">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[260px] flex-col border-r border-[var(--line)] bg-[var(--panel)] p-5 transition-transform lg:static lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center justify-between"><Logo /><button onClick={() => setMobileOpen(false)} className="rounded-lg p-2 lg:hidden" aria-label="Close menu"><X size={20} /></button></div>
      <div className="mt-10 flex flex-1 flex-col"><p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-[var(--ink-soft)]">Your court</p><nav className="space-y-1">{navItems.map(({ label, icon: Icon, count }) => <button key={label} onClick={() => { setActiveNav(label); setMobileOpen(false); }} className={`flex min-h-11 w-full items-center justify-between rounded-xl px-3 text-sm font-semibold transition-colors ${activeNav === label ? "bg-[#1b211e] text-white" : "text-[var(--ink-soft)] hover:bg-[#eef1eb]"}`}><span className="flex items-center gap-3"><Icon size={18} />{label}</span>{count && <span className={`grid h-5 min-w-5 place-items-center rounded-full px-1 text-[10px] ${activeNav === label ? "bg-[var(--lime)] text-[#1b211e]" : "bg-[#e8eee5] text-[#617064]"}`}>{count}</span>}</button>)}</nav><p className="mb-3 mt-9 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-[var(--ink-soft)]">Explore</p><nav className="space-y-1"><a href="#groups" className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-semibold text-[var(--ink-soft)] hover:bg-[#eef1eb]"><Grid2X2 size={18} />Browse groups</a><a href="#leaderboard" className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-semibold text-[var(--ink-soft)] hover:bg-[#eef1eb]"><Trophy size={18} />Site leaderboard</a></nav></div>
      <div className="rounded-2xl bg-[#eef1e9] p-4"><div className="mb-3 flex items-center justify-between"><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--lime)] text-xs font-extrabold">MC</span><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-[#6e7b70]">3.8 rating</span></div><p className="text-sm font-bold">Ready for a game?</p><p className="mt-1 text-xs leading-5 text-[var(--ink-soft)]">Your next win is probably closer than you think.</p></div>
      <div className="mt-5 flex items-center justify-between px-1 text-[var(--ink-soft)]"><button aria-label="Settings" className="rounded-lg p-2 hover:bg-[#eef1eb]"><Settings size={18} /></button><button aria-label="Help" className="rounded-lg p-2 hover:bg-[#eef1eb]"><CircleHelp size={18} /></button><button aria-label="Sign out" className="text-xs font-semibold hover:text-[var(--foreground)]">Sign out</button></div>
    </aside>
    {mobileOpen && <button className="fixed inset-0 z-20 bg-[#182019]/30 lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation" />}
    <main className="min-w-0 flex-1"><header className="flex h-[76px] items-center justify-between border-b border-[var(--line)] bg-[var(--panel)] px-5 sm:px-8 lg:px-10"><button onClick={() => setMobileOpen(true)} className="rounded-lg p-2 lg:hidden" aria-label="Open menu"><Menu size={22} /></button><div className="hidden items-center gap-2 text-sm text-[var(--ink-soft)] sm:flex"><span className="font-semibold text-[var(--foreground)]">{activeNav}</span><ChevronRight size={15} /><span>Fall season</span></div><div className="ml-auto flex items-center gap-3"><button className="hidden rounded-full border border-[var(--line)] p-2.5 text-[var(--ink-soft)] hover:bg-[#f2f5f0] sm:block" aria-label="Search"><Search size={18} /></button><button className="relative rounded-full border border-[var(--line)] p-2.5 text-[var(--ink-soft)] hover:bg-[#f2f5f0]" aria-label="Notifications"><Bell size={18} /><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-[var(--coral)]" /></button><div className="grid h-9 w-9 place-items-center rounded-full bg-[#c8d6b8] text-xs font-extrabold text-[#30402f]">MC</div></div></header>
      <div className="mx-auto max-w-[1440px] px-5 py-7 sm:px-8 sm:py-10 lg:px-10"><section className="fade-up flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-[var(--lime-deep)]">Saturday, September 21</p><h1 className="max-w-[680px] text-3xl font-black tracking-[-.04em] sm:text-5xl">Good morning, Maya<span className="text-[var(--lime-deep)]">.</span></h1><p className="mt-3 max-w-lg text-sm leading-6 text-[var(--ink-soft)]">The courts are calling. Here’s your playbook for the week ahead.</p></div><button className="flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#1b211e] px-5 text-sm font-bold text-white shadow-[0_8px_20px_rgba(27,33,30,.15)] transition-transform hover:-translate-y-0.5"><Plus size={18} />Create a game</button></section>
        <section className="mt-8 grid gap-3 sm:grid-cols-3"><div className="panel rounded-2xl p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--ink-soft)]">My record</p><p className="mt-3 text-3xl font-black tracking-[-.04em]">{currentUser.record}</p><p className="mt-1 text-xs font-semibold text-[#6b8470]">{currentUser.winRate} win rate</p></div><div className="panel rounded-2xl p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--ink-soft)]">Current rank</p><p className="mt-3 flex items-center gap-2 text-3xl font-black tracking-[-.04em]">#{currentUser.rank} <span className="flex items-center text-sm font-bold text-[#6d9a2e]"><ArrowUpRight size={17} />{currentUser.rankMovement}</span></p><p className="mt-1 text-xs font-semibold text-[var(--ink-soft)]">Northside Wolves</p></div><div className="rounded-2xl bg-[#1b211e] p-5 text-white"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a9b6a9]">Playing this week</p><p className="mt-3 text-3xl font-black tracking-[-.04em]">3 <span className="text-base font-semibold text-[#a9b6a9]">games</span></p><p className="mt-1 text-xs font-semibold text-[var(--lime)]">1 spot still open to join</p></div></section>
        <section className="mt-10" id="events"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-xl font-extrabold tracking-tight">Your upcoming games</h2><p className="mt-1 text-sm text-[var(--ink-soft)]">Keep your edge sharp with the right competition.</p></div><div className="flex gap-1 rounded-full bg-[#e8ede7] p-1">{(["All", "Doubles", "Mixed doubles"] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-2 text-xs font-bold transition-colors ${filter === item ? "bg-white text-[var(--foreground)] shadow-sm" : "text-[var(--ink-soft)]"}`}>{item}</button>)}</div></div><div className="grid gap-4 lg:grid-cols-3">{visibleEvents.map((event) => <EventCard key={event.id} event={event} onToggle={toggleEvent} />)}</div></section>
        <div className="mt-10 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="panel rounded-[20px] p-5 sm:p-6" id="groups"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-xl font-extrabold tracking-tight">Your groups</h2><p className="mt-1 text-sm text-[var(--ink-soft)]">Your communities, all in one place.</p></div><a href="#groups" className="text-xs font-bold text-[#6b8f21]">View all</a></div><div className="divide-y divide-[var(--line)]">{groups.map((group) => <div key={group.name} className="flex items-center gap-3 py-4 first:pt-0 last:pb-0"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl text-xs font-black ${group.color === "lime" ? "bg-[var(--lime)]" : group.color === "blue" ? "bg-[var(--blue)]" : "bg-[var(--coral)]"}`}>{group.mark}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{group.name}</p><p className="mt-1 truncate text-xs text-[var(--ink-soft)]">{group.members} members · {group.next}</p></div><span className="hidden rounded-full bg-[#eef2ed] px-2.5 py-1 text-[10px] font-bold text-[var(--ink-soft)] sm:inline">{group.role}</span><ChevronRight size={17} className="text-[#a1ada2]" /></div>)}</div></section><section className="panel rounded-[20px] p-5 sm:p-6" id="leaderboard"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-xl font-extrabold tracking-tight">Northside leaderboard</h2><p className="mt-1 text-sm text-[var(--ink-soft)]">Fall season · all formats</p></div><a href="#leaderboard" className="grid h-9 w-9 place-items-center rounded-full bg-[#eef2ed] text-[#6b8f21]" aria-label="View leaderboard"><ChevronRight size={17} /></a></div><div className="space-y-1">{leaderboard.map((player) => <div key={player.name} className={`flex items-center gap-3 rounded-xl px-2 py-3 ${player.name === currentUser.name ? "bg-[#f0f5d9]" : ""}`}><span className="w-5 text-center text-xs font-bold text-[var(--ink-soft)]">{player.rank}</span><span className="grid h-8 w-8 place-items-center rounded-full bg-[#dfe8db] text-[10px] font-black">{player.initials}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{player.name}</p><p className="text-[11px] text-[var(--ink-soft)]">{player.record} · {player.rating} rating</p></div><span className={`flex items-center text-[11px] font-bold ${player.movement > 0 ? "text-[#6d9a2e]" : "text-[#dd735b]"}`}>{player.movement > 0 ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{Math.abs(player.movement)}</span></div>)}</div></section></div>
        <section className="panel mt-5 rounded-[20px] p-5 sm:p-6"><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-extrabold tracking-tight">Recent results</h2><p className="mt-1 text-sm text-[var(--ink-soft)]">Your last three matches</p></div><a href="#history" className="text-xs font-bold text-[#6b8f21]">Match history</a></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-[var(--line)] text-[10px] font-bold uppercase tracking-[.14em] text-[var(--ink-soft)]"><th className="pb-3">Match</th><th className="pb-3">Event</th><th className="pb-3">Score</th><th className="pb-3">Result</th><th className="pb-3 text-right">Rating change</th></tr></thead><tbody>{recentResults.map((result) => <tr key={result.opponent} className="border-b border-[var(--line)] last:border-0"><td className="py-4 font-bold">{result.opponent}<span className="ml-2 text-xs font-normal text-[var(--ink-soft)]">{result.date}</span></td><td className="py-4 text-[var(--ink-soft)]">{result.event}</td><td className="py-4 font-semibold">{result.score}</td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${result.result === "W" ? "bg-[#e4f3a8] text-[#5c7b1a]" : "bg-[#fde3dd] text-[#b95642]"}`}>{result.result}</span></td><td className={`py-4 text-right font-bold ${result.points.startsWith("+") ? "text-[#6d9a2e]" : "text-[#d66b56]"}`}>{result.points}</td></tr>)}</tbody></table></div></section>
      </div>
    </main>
  </div>;
}
