"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, MapPin, PawPrint } from "lucide-react";

type Match = { id: string; event: string; location: string; scheduledAt: string | null; scores: { sideAScore: number; sideBScore: number }[]; players: { id: string; name: string; side: "A" | "B" }[] };

export default function MatchesPage() {
  const [matches, setMatches] = useState<Match[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/matches").then((response) => response.json()).then((data) => setMatches(data.matches ?? [])).finally(() => setLoading(false)); }, []);
  return <main className="min-h-screen bg-[var(--background)] px-5 py-8 noise sm:px-10"><div className="mx-auto max-w-5xl"><Link href="/" className="flex items-center gap-2 text-xs font-bold text-[var(--lime-deep)]"><ArrowLeft size={14} />Back to dashboard</Link><p className="mt-8 text-xs font-bold uppercase tracking-[.18em] text-[var(--lime-deep)]">Your record</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em] text-[var(--foreground)]">Match history.</h1><p className="mt-3 text-sm text-[var(--ink-soft)]">Every result, score, and opponent in one place.</p><section className="mt-8 space-y-3">{loading ? <div className="rounded-[20px] border border-[var(--line)] bg-[var(--panel)] p-6 text-sm text-[var(--ink-soft)]">Loading matches...</div> : matches.length === 0 ? <div className="rounded-[20px] border border-[var(--line)] bg-[var(--panel)] p-8 text-center"><PawPrint size={22} className="mx-auto text-[var(--lime-deep)]" /><p className="mt-3 font-bold text-[var(--foreground)]">No matches recorded yet.</p><p className="mt-2 text-sm text-[var(--ink-soft)]">Record your first result after a game to start your history.</p></div> : matches.map((match) => <article key={match.id} className="rounded-[20px] border border-[var(--line)] bg-[var(--panel)] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="flex-1"><h2 className="font-extrabold text-[var(--foreground)]">{match.event}</h2><div className="mt-2 flex flex-wrap gap-4 text-xs text-[var(--ink-soft)]"><span className="flex items-center gap-1"><MapPin size={14} />{match.location}</span><span className="flex items-center gap-1"><CalendarDays size={14} />{match.scheduledAt ? new Date(match.scheduledAt).toLocaleDateString() : "Recently"}</span></div></div><div className="flex flex-wrap gap-2">{match.scores.map((score, index) => <span key={index} className="rounded-lg bg-[#1c2a1a] px-3 py-2 text-sm font-black text-[var(--foreground)]">{score.sideAScore} - {score.sideBScore}</span>)}</div></div><p className="mt-4 border-t border-[var(--line)] pt-3 text-xs text-[var(--ink-soft)]">{match.players.map((player) => player.name).join(" · ")}</p></article>)}</section></div></main>;
}
